### ISSUE TITLE
Details tab is unselectable when regular descriptions are missing

### ISSUE THREAD

**Issue by malewins** [malewins/SEQing#64]
When no regular description file is supplied but only the advanced one, the advanced description tab is not selectable.

**Comment by YBramkamp** [comment]
Cannot reproduce this issue. Tab worked when testing without regular descriptions. The tab not being selectable hints at an issue with your advanced description file. Added some additional print()s to determine if that is the case

**Comment by YBramkamp** [comment]
Issue was related to missing field in column header. A check to try and detect this in the future has been implemented in cfe117b
